version: "2"
services:
  postgres:
    build: ./db
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: postgres

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_PASS: claire
      RABBITMQ_DEFAULT_USER: claire
    image: "rabbitmq:3.6.10"

  redis:
    environment:
      REDIS_DEFAULT_PASS: claire
      REDIS_DEFAULT_USER: claire
    image: "redis:alpine"

  mongodb:
    image: mongo:3.4
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    logging:
      driver: none

  service:
    container_name: clairvoyance_service_analytics
    build: .
    depends_on:
      - postgres
      - redis
      - mongodb
    ports:
      - "8080:3000"
    volumes:
      - "./:/app"
    entrypoint: ["tail", "-f", "/dev/null"]
